### PR TITLE
Services section made

### PR DESCRIPTION
**Pull request by tejus0**

### CODE REVIEW

**Comment by tejus0** [comment]
services section

**Comment by tejus0** [comment]
@SP-XD, I have made a pull request to you just now. And I instantly got message of rejection of my PR from hacktoberfest. Can you tell me why me PR got rejected even when you haven't seen it yet. Is there anything wrong I did to make a PR? Uploading z2{ae36bb} (1cca9852-0d06-45a6-96ba-655b09379049 id=0x7f0a03cd tag=BaseCommentFragment) …

**Comment by tejus0** [comment]
@SP-XD, I have made a pull request to you just now. And I instantly got message of rejection of my PR from hacktoberfest. Can you tell me why me PR got rejected even when you haven't seen it yet. Is there anything wrong I did to make a PR?

**Comment by SP-XD** [comment]
@tejus0 Hi, You have removed all my css code. 
What are you doing?
image

**Comment by SP-XD** [comment]
@tejus0 Please check your code before making a PR

**Comment by tejus0** [comment]
Hey @SP-XD what page are you talking about , as it is working fine in my device . 
image

**Comment by tejus0** [comment]
And the section i made is also fine  Let's take a look at the pics of my work .
image
image

**Comment by SP-XD** [comment]
@tejus0 Check the commits here, Your changes have removed most code of my styles.css and there
I found the problem You have made a pr with the wrong branch here. Your beta branch doesn't contain the changes that you are making a PR with. please make a new PR with your services branch or where all your changes are there.

**Comment by tejus0** [comment]
> @tejus0 Check the commits here, Your changes have removed most code of my styles.css and there
> I found the problem You have made a pr with the wrong branch here. Your beta branch doesn't contain the changes that you are making a PR with. please make a new PR with your services branch or where all your changes are there.

Hey @SP-XD i have made a second PR with the help of my friend. So now check the latest one.

**Comment by SP-XD** [comment]
#12 accepted so closing this
@tejus0 happy hackking!

**Pull request closed without merging**
