### PR TITLE
Make HTML valid

### PR DESCRIPTION
**Pull request by ashishpetwal**
I have updated the index.html and validated completely with validator.w3.org. The only issue left is with the masked image which can be neglected!
Thanks for the oppurtunity...
Kindly merge the PR and close the issue...

### CODE REVIEW

**Comment by ashishpetwal** [comment]
@SP-XD Kindly check

**Comment by SP-XD** [comment]
> @SP-XD Kindly check

image

There are still many errors left, please resolve them.
Also you have removed some opening tags, fix them.
leave the mask-type.
and for the images try with width and height at 100%.

**Comment by SP-XD** [comment]
Also Hi @ashishpetwal sync your branch with latest changes from upstream, before adding changes

**Comment by ashishpetwal** [comment]
@SP-XD I have updated the HTML file with valid changes and now only the mask type error is left, rest are resolved

**Pull request merged**
