### PR TITLE
zoom on hover project card

### PR DESCRIPTION
**Pull request by yasaswini999**
image
@SP-XD let me know if you had any changes and if you liked my contribution pls add hacktoberfest-accepted label

### CODE REVIEW

**Comment by SP-XD** [comment]
@yasaswini999 are you still working on it? else I would close it

**Comment by yasaswini999** [comment]
i made the requested changes on the day itself

**Comment by SP-XD** [comment]
> i made the requested changes on the day itself

I added somes above reviews to adapt the new change to the overall design, those are pending.

**Comment by SP-XD** [comment]
skipping this effect as no response from @yasaswini999

**Pull request closed without merging**
